spring:
  profiles:
    active: local
  application:
    name: event-producer-api
app:
  context:
    path: /producer/eventTrigger

---
spring:
  profiles: local
  kafka:
    template:
      default-topic: fuel-events
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
   
server:
  port: 8082