app:
    context:
        path: /consumer/eventTrigger
server: 
    port: 8081
    
spring:
    application:
        name: event-receiving-api
        
    kafka:
        template:
            default-topic: fuel-events
        bootstrap-servers: 127.0.0.1:9092
        consumer:
            enable-auto-commit: false
            group-id: fuel-cap-events-listener-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        listener:
            missing-topics-fatal: false
            
app-cache:
    scheduled-time:0 0/25 * * * *
fuel-api:
    url: http://localhost:8083/fuelPrice/v1/

